tinyMCE.addI18n('hu.advanced',{
style_select:"Stílusok",
font_size:"Betűméret",
fontdefault:"Betűtípus",
block:"Formátum",
paragraph:"Paragrafus",
div:"Div",
address:"Cím",
pre:"Előformázott",
h1:"Címsor 1",
h2:"Címsor 2",
h3:"Címsor 3",
h4:"Címsor 4",
h5:"Címsor 5",
h6:"Címsor 6",
blockquote:"Idézet",
code:"Kód",
samp:"Kód minta",
dt:"Meghatározás",
dd:"Meghatározás kifejtés",
bold_desc:"Félkövér (Ctrl+B)",
italic_desc:"Dőlt (Ctrl+I)",
underline_desc:"Aláhúzott (Ctrl+U)",
striketrough_desc:"Áthúzott",
justifyleft_desc:"Balra zárt",
justifycenter_desc:"Középre zárt",
justifyright_desc:"Jobbra zárt",
justifyfull_desc:"Sorkizárt",
bullist_desc:"Rendezetlen lista",
numlist_desc:"Rendezett lista",
outdent_desc:"Kihúzás",
indent_desc:"Behúzás",
undo_desc:"Visszavon (Ctrl+Z)",
redo_desc:"Mégis csinál (Ctrl+Y)",
link_desc:"Link beszúrása/szerkesztése",
unlink_desc:"Link megszűntetése",
image_desc:"Kép beszúrása/szerkesztése",
cleanup_desc:"Rendetlen kód takarítása",
code_desc:"HTML forrás szerkesztése",
sub_desc:"Alsó index",
sup_desc:"Felső index",
hr_desc:"Vizszintes elválasztó beszúrása",
removeformat_desc:"Formázás eltávolítása",
custom1_desc:"Az ön egyedi leírása",
forecolor_desc:"Szövegszín választás",
backcolor_desc:"Háttérszín választás",
charmap_desc:"Speciális karakter beszúrása",
visualaid_desc:"Vezetővonalak/nemlátható elemek ki/be kapcsolása",
anchor_desc:"Horgony beszúrása/szerkesztése",
cut_desc:"Kivágás",
copy_desc:"Másolás",
paste_desc:"Beszúrás",
image_props_desc:"Kép tulajdonságai",
newdocument_desc:"Új dokumentum",
help_desc:"Segítség",
blockquote_desc:"Idézet",
clipboard_msg:"A Másolás/Kivágás/Beszúrás funkciók nem elérhetőek Mozilla és Firefox alatt.\r\nKíván többet tudni erről a dologról?",
path:"Útvonal",
newdocument:"Biztosan törli az összes megjegyzést?",
toolbar_focus:"Eszközgombokra ugrás - Alt+Q, Szerkesztőhöz ugrás - Alt-Z, Elemútvonalhoz ugrás - Alt-X",
more_colors:"Több szín"
});