tinyMCE.addI18n('hu.advanced_dlg',{
about_title:"A TinyMCE-ről",
about_general:"Rólunk",
about_help:"Segítség",
about_license:"Licensz",
about_plugins:"Pluginok",
about_plugin:"Plugin",
about_author:"Szerző",
about_version:"Verzió",
about_loaded:"Betöltött plugin-ok",
anchor_title:"Horgony beszúrása/szerkesztése",
anchor_name:"Horgonynév",
code_title:"HTML forrás szerkesztő",
code_wordwrap:"Szöveg tördelés",
colorpicker_title:"Színválasztás",
colorpicker_picker_tab:"Választó",
colorpicker_picker_title:"Színválasztó",
colorpicker_palette_tab:"Paletta",
colorpicker_palette_title:"Paletta színek",
colorpicker_named_tab:"Nevezettek",
colorpicker_named_title:"Nevezett színek",
colorpicker_color:"Szín:",
colorpicker_name:"Név:",
charmap_title:"Egyedikarakter választó",
image_title:"Kép beszúrása/szerkesztése",
image_src:"Kép URL",
image_alt:"Kép leírás",
image_list:"Kép lista",
image_border:"Keret",
image_dimensions:"Dimenziók",
image_vspace:"Függőleges táv",
image_hspace:"Vízszintes táv",
image_align:"Igazítás",
image_align_baseline:"Baseline",
image_align_top:"Fent",
image_align_middle:"Középen",
image_align_bottom:"Lent",
image_align_texttop:"Szöveg tetejéhez",
image_align_textbottom:"Szöveg aljához",
image_align_left:"Balra",
image_align_right:"Jobbra",
link_title:"Link beszúrása szerkesztése",
link_url:"Link URL",
link_target:"Cél",
link_target_same:"Link azonos ablakba nyitása",
link_target_blank:"Link új ablakba nyitása",
link_titlefield:"Cím",
link_is_email:"A beírt URL e-mail címnek tűnik, kívánja a szükséges mailto:-t elé tenni?",
link_is_external:"A beírt URL külső hivatkozásnak tűnik, kívánja a szükséges http://-t elé tenni?",
link_list:"Link lista"
});